# Generated by Django 2.0.1 on 2018-01-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180115_0117'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rock',
            table='rocks',
        ),
    ]
